services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: tnkshop
      MYSQL_DATABASE: tnk-project
      MYSQL_USER: tnkuser
      MYSQL_PASSWORD: tnksupersecret
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always

volumes:
  db_data:
